//
//  UserDefaultConst.h
//  mmcS2
//
//  Created by 肖君 on 16/11/6.
//  Copyright © 2016年 johnxiao. All rights reserved.
//

#ifndef UserDefaultConst_h
#define UserDefaultConst_h

#define USER_DEFAULT_PRE_CONNECTED_DEVICE_UUIDSTRING @"USER_DEFAULT_PRE_CONNECTED_DEVICE_UUIDSTRING"
#define USER_DEFAULT_LAST_TEMPERATURE_INDEX @"USER_DEFAULT_LAST_TEMPERATURE_INDEX"
#define USER_DEFAULT_USER_MODE @"USER_DEFAULT_USER_MODE"

#define USER_DEFAULT_SHOW_THUMB @"USER_DEFAULT_SHOW_THUMB"
#define USER_DEFAULT_SHOW_OTHERFINGER @"USER_DEFAULT_SHOW_OTHERFINGER"
#define USER_DEFAULT_SHOW_GUIDE @"USER_DEFAULT_SHOW_GUIDE"
#define USER_DEFAULT_SHOW_TYPE @"USER_DEFAULT_SHOW_TYPE"
#define USER_DEFAULT_LOCAL_VERSION @"USER_DEFAULT_LOCAL_VERSION"
#define USER_DEFAULT_CURRENT_VERSION 2


#endif /* UserDefaultConst_h */
